### ISSUE TITLE
Documentation Epic

### ISSUE THREAD

**Issue by navarr** [swiftotter/den#147]
- [ ] https://github.com/swiftotter/den/issues/144
- [ ] https://github.com/swiftotter/den/issues/146
- [ ] https://github.com/swiftotter/den/issues/138
- [ ] https://github.com/swiftotter/den/issues/65
